version: "3.9"

services:
  db:
    image:mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  platform:
    image: ${dockerOrgName}/:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db

